# Generated by Django 4.2.5 on 2023-10-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIEFAapp', '0002_alter_stock_graph_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='graph_data',
        ),
    ]
