# Generated by Django 4.2.5 on 2023-10-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIEFAapp', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='conf_interval',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='hist_accuracy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
