# Generated by Django 4.2.5 on 2023-10-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIEFAapp', '0006_stock_conf_interval_stock_hist_accuracy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_stocks',
        ),
        migrations.AlterField(
            model_name='stock',
            name='users',
            field=models.ManyToManyField(to='AIEFAapp.profile'),
        ),
    ]
