# Generated by Django 4.2.5 on 2023-10-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIEFAapp', '0008_alter_stock_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='users',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_stocks',
            field=models.ManyToManyField(to='AIEFAapp.stock'),
        ),
    ]
