# Generated by Django 4.2.5 on 2023-11-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIEFAapp', '0009_remove_stock_users_profile_user_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='conf_interval',
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIEFAapp.stock')),
            ],
        ),
    ]
